type Query {
    recipe(id: ID): Recipe
    pid: Int
}
type Recipe {
    id: ID!
    name: String!
    ingredients: [Ingredient]
    steps: String
}
type Ingredient {
    id: ID!
    name: String!
    quantity: String!
}